# Generated by Django 5.2.6 on 2025-09-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="updated_at",
        ),
    ]
