# Generated by Django 5.2.6 on 2025-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_remove_location_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
