# Generated by Django 5.2.7 on 2025-10-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_location_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
