# Generated by Django 5.2.7 on 2025-11-11 19:08

from decimal import Decimal
from django.db import migrations


def create_initial_locations(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')

    initial_locations = [
        {
            "name": "Praça Getúlio Vargas",
            "description": "Principal praça da cidade de Patos-PB, ponto de encontro e eventos culturais",
            "latitude": Decimal("-7.02636800"),
            "longitude": Decimal("-37.27701000"),
        },
        {
            "name": "Igreja Matriz de Patos",
            "description": "Igreja histórica no centro da cidade, importante patrimônio arquitetônico",
            "latitude": Decimal("-7.02345600"),
            "longitude": Decimal("-37.28012300"),
        },
        {
            "name": "Museu do Sertão",
            "description": "Museu que preserva a cultura e história do sertão paraibano",
            "latitude": Decimal("-7.02789000"),
            "longitude": Decimal("-37.27567800"),
        },
        {
            "name": "Teatro Municipal de Patos",
            "description": "Principal teatro da cidade, apresenta peças e shows culturais",
            "latitude": Decimal("-7.02456700"),
            "longitude": Decimal("-37.27823400"),
        },
        {
            "name": "Parque da Cidade",
            "description": "Área verde com playground e trilhas para caminhadas",
            "latitude": Decimal("-7.02901200"),
            "longitude": Decimal("-37.27345600"),
        },
    ]

    for location_data in initial_locations:
        Location.objects.create(**location_data)


def remove_initial_locations(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    location_names = [
        "Praça Getúlio Vargas",
        "Igreja Matriz de Patos",
        "Museu do Sertão",
        "Teatro Municipal de Patos",
        "Parque da Cidade"
    ]
    Location.objects.filter(name__in=location_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.RunPython(create_initial_locations, reverse_code=remove_initial_locations),
    ]
