# Generated by Django 5.2.6 on 2025-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("tourist_spot", "Ponto Turístico"),
                            ("event", "Evento"),
                            ("establishment", "Estabelecimento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categories",
                "ordering": ["name"],
            },
        ),
    ]
