# Generated by Django 5.2.6 on 2025-10-02 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteiro",
                "verbose_name_plural": "Roteiros",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("tourist_spot", "Ponto Turístico"),
                            ("event", "Evento"),
                        ],
                        max_length=15,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                ("estimated_arrival", models.TimeField(blank=True, null=True)),
                ("estimated_departure", models.TimeField(blank=True, null=True)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="itineraries.itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Roteiro",
                "verbose_name_plural": "Itens dos Roteiros",
                "ordering": ["itinerary", "order"],
                "unique_together": {("itinerary", "order")},
            },
        ),
    ]
