# Generated by Django 5.2.6 on 2025-10-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itineraryitem",
            options={
                "ordering": ["itinerary", "order"],
                "verbose_name": "itinerary item",
                "verbose_name_plural": "itinerary items",
            },
        ),
    ]
