# Generated by Django 5.2.6 on 2025-10-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_date", "name"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
