# Generated by Django 5.2.6 on 2025-10-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
    ]
