# Generated by Django 5.2.6 on 2025-10-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="establishment",
            options={
                "ordering": ["name"],
                "verbose_name": "Establishment",
                "verbose_name_plural": "Establishments",
            },
        ),
        migrations.AlterModelOptions(
            name="touristspot",
            options={
                "ordering": ["name"],
                "verbose_name": "Tourist Spot",
                "verbose_name_plural": "Tourist Spots",
            },
        ),
    ]
