# Generated by Django 5.2.8 on 2025-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_establishment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_spots/'),
        ),
    ]
